# Generated by Django 4.1 on 2022-08-26 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdescripcion', models.CharField(max_length=100)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_form', to='formulario.formulario')),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
    ]
