# Generated by Django 4.1 on 2022-10-15 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_estado_proyecto_estado_us_sprint_user_story_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='id_sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.sprint'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='id_proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.proyecto'),
        ),
        migrations.CreateModel(
            name='Usuario_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.proyecto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateField(auto_now=True)),
                ('id_user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user_story')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
