# Generated by Django 4.1 on 2022-10-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_backlog_id_sprint_sprint_id_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='id_formulario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.formulario'),
        ),
    ]
